PADDLE_API_KEY=pdl_sdbx_apikey_01m3026e8tt9e8e9btpy6qwrf1_zR5TaSwPTN7vmk1p9GWS5d_Ad7
PADDLE_ENVIRONMENT=sandbox
PADDLE_WEBHOOK_SECRET=pdl_ntfset_01m307wjfgb2gjb7g56rrvpb4e_sd7bleevgIeZdO8zlTM5vC8N4X2Qiyjv
PADDLE_CLIENT_TOKEN=test_e65815970f72a0833271f0cff74
PADDLE_GRACE_PERIOD_DAYS=10
