CREATE TABLE conversation_read_states (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT    NOT NULL REFERENCES tenants (id),
    conversation_id      BIGINT    NOT NULL REFERENCES conversations (id),
    user_id              BIGINT    NOT NULL REFERENCES users (id),
    last_read_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_read_message_id BIGINT    REFERENCES messages (id),
    CONSTRAINT uq_conversation_read_states UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_conversation_read_states_user ON conversation_read_states (user_id, last_read_at);
CREATE INDEX idx_conversation_read_states_tenant ON conversation_read_states (tenant_id, user_id);
