ALTER TABLE branches
    ADD COLUMN hours_configured BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE branch_hours
    ALTER COLUMN open_time DROP NOT NULL,
    ALTER COLUMN close_time DROP NOT NULL;

CREATE INDEX idx_branch_hours_branch_day ON branch_hours (branch_id, day_of_week);

CREATE TABLE branch_hour_exceptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenants (id),
    branch_id       BIGINT       NOT NULL REFERENCES branches (id),
    exception_date  DATE         NOT NULL,
    closed          BOOLEAN      NOT NULL DEFAULT FALSE,
    description     VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_branch_hour_exception_date UNIQUE (branch_id, exception_date)
);

CREATE INDEX idx_branch_hour_exceptions_branch_date ON branch_hour_exceptions (branch_id, exception_date);

CREATE TABLE branch_hour_exception_intervals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exception_id  BIGINT NOT NULL REFERENCES branch_hour_exceptions (id) ON DELETE CASCADE,
    open_time     TIME   NOT NULL,
    close_time    TIME   NOT NULL
);

CREATE INDEX idx_branch_hour_exception_intervals_exception
    ON branch_hour_exception_intervals (exception_id);
