CREATE TABLE account_deletion_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id),
    reason       VARCHAR(500),
    status       VARCHAR(32)  NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    block_code   VARCHAR(64),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uq_account_deletion_requests_token_hash ON account_deletion_requests (token_hash);
CREATE INDEX idx_account_deletion_requests_user_status ON account_deletion_requests (user_id, status);
CREATE INDEX idx_account_deletion_requests_created ON account_deletion_requests (created_at);
