-- Paddle Billing: plan catalog identifiers, tenant subscription lifecycle, webhook ledger.

ALTER TABLE plans
    ADD COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    ADD COLUMN annual_price NUMERIC(10, 2),
    ADD COLUMN paddle_product_id VARCHAR(64),
    ADD COLUMN paddle_monthly_price_id VARCHAR(64),
    ADD COLUMN paddle_annual_price_id VARCHAR(64),
    ADD COLUMN updated_at TIMESTAMP;

CREATE INDEX idx_plans_paddle_product ON plans (paddle_product_id);
CREATE INDEX idx_plans_paddle_monthly_price ON plans (paddle_monthly_price_id);
CREATE INDEX idx_plans_paddle_annual_price ON plans (paddle_annual_price_id);

ALTER TABLE subscriptions
    ADD COLUMN paddle_customer_id VARCHAR(64),
    ADD COLUMN paddle_subscription_id VARCHAR(64),
    ADD COLUMN paddle_transaction_id VARCHAR(64),
    ADD COLUMN billing_cycle VARCHAR(20),
    ADD COLUMN currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    ADD COLUMN current_period_starts_at TIMESTAMP,
    ADD COLUMN next_billing_at TIMESTAMP,
    ADD COLUMN last_payment_succeeded_at TIMESTAMP,
    ADD COLUMN first_payment_failed_at TIMESTAMP,
    ADD COLUMN grace_period_ends_at TIMESTAMP,
    ADD COLUMN suspended_at TIMESTAMP,
    ADD COLUMN scheduled_change_action VARCHAR(40),
    ADD COLUMN scheduled_change_effective_at TIMESTAMP;

CREATE UNIQUE INDEX uq_subscriptions_paddle_subscription_id
    ON subscriptions (paddle_subscription_id)
    WHERE paddle_subscription_id IS NOT NULL;

CREATE INDEX idx_subscriptions_paddle_customer ON subscriptions (paddle_customer_id);
CREATE INDEX idx_subscriptions_grace ON subscriptions (status, grace_period_ends_at);

CREATE TABLE billing_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paddle_event_id   VARCHAR(80) NOT NULL,
    event_type        VARCHAR(80) NOT NULL,
    occurred_at       TIMESTAMP,
    received_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at      TIMESTAMP,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    payload           JSONB       NOT NULL,
    error_message     TEXT
);

CREATE UNIQUE INDEX uq_billing_events_paddle_event_id ON billing_events (paddle_event_id);
CREATE INDEX idx_billing_events_type ON billing_events (event_type);
CREATE INDEX idx_billing_events_status ON billing_events (processing_status);
