-- Self-service clinic signup: TENANT_OWNER, invitations, signup ledger, trial policy.

INSERT INTO roles (code, name_es, name_en, description_es, description_en, system_role)
SELECT 'TENANT_OWNER',
       'Propietario de veterinaria',
       'Clinic owner',
       'Propietario y administrador principal de una veterinaria.',
       'Owner and primary administrator of a veterinary clinic.',
       TRUE
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE code = 'TENANT_OWNER');

INSERT INTO role_permissions (role_id, permission_id)
SELECT owner.id, rp.permission_id
FROM roles owner
JOIN roles admin ON admin.code = 'TENANT_ADMIN'
JOIN role_permissions rp ON rp.role_id = admin.id
WHERE owner.code = 'TENANT_OWNER'
  AND NOT EXISTS (
        SELECT 1 FROM role_permissions existing
        WHERE existing.role_id = owner.id
          AND existing.permission_id = rp.permission_id
  );

ALTER TABLE platform_settings
    ADD COLUMN IF NOT EXISTS max_clinics_per_owner INT NOT NULL DEFAULT 1;

UPDATE platform_settings
SET max_clinics_per_owner = 1
WHERE max_clinics_per_owner IS NULL;

-- Existing accounts never completed email verification. Keep them usable.
UPDATE users
SET email_verified = TRUE
WHERE email_verified = FALSE;

CREATE TABLE IF NOT EXISTS clinic_signups (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    BIGINT       NOT NULL REFERENCES users (id),
    tenant_id                  BIGINT       REFERENCES tenants (id),
    email                      VARCHAR(180) NOT NULL,
    status                     VARCHAR(40)  NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    plan_id                    BIGINT       REFERENCES plans (id),
    billing_cycle              VARCHAR(20),
    requested_slug             VARCHAR(80),
    terms_accepted_at          TIMESTAMP,
    last_verification_sent_at  TIMESTAMP,
    checkout_created_at        TIMESTAMP,
    completed_at               TIMESTAMP,
    created_at                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_clinic_signups_user_open
    ON clinic_signups (user_id)
    WHERE status IN ('PENDING_EMAIL_VERIFICATION', 'EMAIL_VERIFIED', 'PENDING_PAYMENT');

CREATE INDEX IF NOT EXISTS idx_clinic_signups_email ON clinic_signups (email);
CREATE INDEX IF NOT EXISTS idx_clinic_signups_tenant ON clinic_signups (tenant_id);
CREATE INDEX IF NOT EXISTS idx_clinic_signups_status ON clinic_signups (status);

CREATE TABLE IF NOT EXISTS staff_invitations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT       NOT NULL REFERENCES tenants (id),
    invited_by    BIGINT       REFERENCES users (id),
    email         VARCHAR(180) NOT NULL,
    first_name    VARCHAR(80),
    last_name     VARCHAR(120),
    role_code     VARCHAR(40)  NOT NULL,
    token_hash    VARCHAR(128) NOT NULL UNIQUE,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    expires_at    TIMESTAMP    NOT NULL,
    accepted_at   TIMESTAMP,
    accepted_by   BIGINT       REFERENCES users (id),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_invitations_tenant_email_pending
    ON staff_invitations (tenant_id, lower(email))
    WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_staff_invitations_tenant ON staff_invitations (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_staff_invitations_expires ON staff_invitations (expires_at);

CREATE INDEX IF NOT EXISTS idx_email_verification_user ON email_verification_tokens (user_id, used, expires_at);
CREATE INDEX IF NOT EXISTS idx_memberships_user ON tenant_memberships (user_id, status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant_started ON subscriptions (tenant_id, started_at DESC);

-- Existing tenants already have memberships; keep TENANT_ADMIN for compatibility.
-- New self-service clinics use TENANT_OWNER. Superadmin creates can also assign TENANT_OWNER.
