server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api:8080/api/;
    proxy_set_header Host $host;
    proxy_set_header Authorization $http_authorization;
  }

  location /v3/ {
    proxy_pass http://api:8080/v3/;
  }

  location /swagger-ui {
    proxy_pass http://api:8080/swagger-ui;
  }

  location = / {
    rewrite ^ /home/index.html last;
  }

  location = /terms {
    rewrite ^ /terminos/index.html last;
  }

  location = /terms/ {
    rewrite ^ /terminos/index.html last;
  }

  location = /privacy {
    rewrite ^ /privacidad/index.html last;
  }

  location = /privacy/ {
    rewrite ^ /privacidad/index.html last;
  }

  location = /refund {
    rewrite ^ /reembolsos/index.html last;
  }

  location = /refund/ {
    rewrite ^ /reembolsos/index.html last;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
